### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Chernoskill** [tigrouind/AITD-roomviewer#1]
Hello, 
first of all: Thanks for creating this asset.

I tried to use it but there is no bms file included so I can't select it with QuickBMS as instructed in the readme file. Did I do something wrong or is the readme file possible outdated?

Kind regards

Robert

**Comment by tigrouind** [comment]
Hello.
The bms file can be found here  : [AITD room viewer 1.1.14](https://github.com/tigrouind/AITD-roomviewer/releases/tag/1.1.14). I will edit the readme file to redirect to that page.
