### ISSUE TITLE
Does this rip models or what should I use to for ripping models from the viewer?

### ISSUE THREAD

**Issue by Philhubk98** [tigrouind/AITD-roomviewer#10]
Hi. I download this to see if I can rip models from the game with the model viewer but so far I couldn't find any way to rip them from the viewer yet! I would appreciate some help on ripping some models of the first 3 games and Jack in the Dark.

**Comment by tigrouind** [comment]
Hello. Export of models is currently not possible. The only way is to modify the code (there is no quick way to achieve this).
May I ask why you need this ? (what do you intend to do ?)

**Comment by Philhubk98** [comment]
> 

Thats weird! Somehow a guy from Sketchfab managed to pull it off and he only rip a few characters. I tried asking him how he did it but he simply block me and he deleted all of his models there! 

Seriously I don't know what his problem was, I did ask him nicely and I guess he thought I was harassing him? 

Anyway, I want those 3d models so I can save them as dae for easier viewing and access with Blender. I need those models for future reference as I plan to draw the characters on ms paint soon and the models themselves might come in handy in the future for any purposes. 

Im sure there are other fans who might want the models for themselves. I would be very happy to share these models with the world so they don't have to go through the trouble with ripping the models by themselves. 

Im just a very nice and generous individual who want to make the models from this game easier to find as there currently nobody preserving the 3d models on the internet possibly due to how badly obscure the first 3 games were and the whole franchise was dormant for a very long time, Im sure lots of gamers easily forgot about this game and I was one of them who grow up with Alone in the Dark 2 better known as One Eyes Jack's Revenge on the Playstation 1. 

I just want the 3d models thats all, I currently do not have any big plans on what to do with them and only want to rip them for preservation sake. Hope you understand! 

I don't know how that guy from Sketchfab did it and I had no idea its that complicated to rip them but if there any way you can help I would gladly appreciate it! 

Best regards.

**Comment by tigrouind** [comment]
I have added support to export models to OBJ format. There is a new option in the main menu. Alternatively, you can also press X key. If you hold shift, it will export all models (this take a while). 

To view vertex colors, you have to create custom shaders. Please take a look at this [page](https://github.com/tigrouind/AITD-roomviewer/tree/master?tab=readme-ov-file#obj-export)

Please keep in mind those assets are still copyrighted (eg: it's not a good idea to sell models on an online platform). THQ Nordic currently hold the rights of the Alone in the Dark franchise.

**Comment by Philhubk98** [comment]
I don't sell 3d models. I only want to preserve old models from old games for history and viewing purposes. I could not find any official art of those characters and there are currently no other sources I can use for reference with drawing and recreating any of the characters and settings from the trilogy. Hope you understand and thanks for helping!

**Comment by tigrouind** [comment]
> I don't sell 3d models. 

I wrote it as info. This might be useful for other users that also want to export models.
Please let me know if you have any issues. If I don't hear from you in a few days, I will close the thread.
