### ISSUE TITLE
AITD3 not working with DosBOX

### ISSUE THREAD

**Issue by Cribblers** [tigrouind/AITD-roomviewer#12]
It doesn't seem to work, AITD2 works well, but 3 doesn't.
Sorry for the brevity.

**Comment by tigrouind** [comment]
There was indeed a bug, AITD3 was no longer detected correctly. It has been introduced when I added support for the demo version. It's now fixed. Can you try the new release I've just uploaded (or from source if you have Unity installed) and tell me if it fixes the problem for you too?

**Comment by Cribblers** [comment]
It does work! Thank you so much!
Btw, do you have a discord so we could talk about the tool? I really don't want to flood the github with issues threads, hahaha.

**Comment by tigrouind** [comment]
I have added a link on my github profile
