### ISSUE TITLE
is there a way to rip sprites of the backgrounds and menu buttons from the DOS versions?

### ISSUE THREAD

**Issue by Philgamerk98** [tigrouind/AITD-roomviewer#13]
While it might be easier to do this on windows ports, the DOS versions might have content that the Windows versions don't have due to DOS being the original releases. Im also considering to look at the demo ones for any beta content buried in the demos! I just need to know if you could add a feature for dumping sprites of the backgrounds and menu graphics or maybe suggest what tool would be best and right for me to use for ripping the backgrounds and menu graphics? I would gladly appreciate your help. Thanks!

**Comment by tigrouind** [comment]
For extracting backgrounds, you can use [PAKExtract](https://github.com/tigrouind/AITD-tools?tab=readme-ov-file#pakextract) from AITD-tools. It's unlikely you will find some unused stuff lot of people already checked it.

Menu graphics : I don't know any tool that can do that automatically and I don't have time to write code. 
Anyway, here some information about it (in case somebody is interested) : 

* menu data should be located in 4th entry of ITD_RESS.PAK. PAKExtract can be used to extract that file.
* that file contains several sprites (used for drawing menus and such). 
* the first two bytes of that file is a pointer to the data. For example sprite 6 pointer is located at 6 x 2 = offset 12.
* each sprite start with a header, specifying width and height then it's followed by the raw pixel data. Here is an [example](https://github.com/yaz0r/FITD/blob/402ba78824a5b6268644de60727ea62fbdb70c57/FitdLib/aitdBox.cpp#L3).

**Comment by tigrouind** [comment]
Menu graphics : everything is made using those sprites : 
![Untitled](https://github.com/user-attachments/assets/7e1b55df-ccff-4f2a-a3f1-3767eec86d72)
