### ISSUE TITLE
Models Not Working When Edited?

### ISSUE THREAD

**Issue by MrQuetch** [tigrouind/AITD-roomviewer#3]
Hi there, Tigrouind.

I'm quite fascinated by your work on previewing the rooms and models from AITD.

I was planning on writing my own model exporter to convert models from Autodesk 3DS to AITD.

I have noticed that when I first open the program, everything works fine - the rooms and models.

When I edit any of the models using a hex editor, save the changes, and return, I can clearly see them.

However, when I stop running the Unity program, and return to the models, they no longer exist.

It appears that Unity cannot find the directory, even though it clearly exists.

I have found that the only work around is to make a new "GAMEDATA" folder with a different name, and change that name in the source code so Unity can see the new folder with the same data in it.

I was wondering if it may be possible to fix this bug, so I can use the same folder, and make changes without this hassle?

Thank you in advance.

**Comment by tigrouind** [comment]
> It appears that Unity cannot find the directory, even though it clearly exists.

It might be related to some missing file system permissions on GAMEDATA folder. Could you try to run Unity executable with administrator rights and see if it fix the problem ? (right click on exe, choose "run as administrator")
