### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by shprotru** [tigrouind/AITD-roomviewer#4]
1. Can I ask you to make more detailed models processing, to get something like https://pastebin.com/ic9EWn7W when loading a model? // I have no unity to make this
2. Is it possible to make export models to .obj or .blend file?

**Comment by tigrouind** [comment]
1. bodys (aka 3d models) internal format is not documented.
However, exporting data as in the example you give should not be too hard.
Loading models is done here : [ModelLoader.cs](https://github.com/tigrouind/AITD-roomviewer/blob/6aa46b600336bee76f1c69ee04b5052b04e71360/Assets/Scripts/ModelLoader.cs#L48)
I took a old version before bones support as it is easier to read.

2. there is currently no such option

**Comment by tigrouind** [comment]
1) Sorry but I don't have time to do this.
Anyway If you have some C# knowledge, this should not be too hard. There is no need to have Unity installed. Any C# editor would do (eg : Visual Code or SharpDevelop if you don't have VisualStudio installed). The code where model is loaded is [here](https://github.com/tigrouind/AITD-roomviewer/blob/6aa46b600336bee76f1c69ee04b5052b04e71360/Assets/Scripts/ModelLoader.cs#L48).
2) this is currently not possible.
