### ISSUE TITLE
Loading backgrounds

### ISSUE THREAD

**Issue by demonixis** [tigrouind/AITD-roomviewer#5]
Hello,
I forked your project and I would like to know how to load backgrounds. Is there a reference documentation somewhere? 

Thank you.

**Comment by tigrouind** [comment]
AITD room viewer does not support loading backgrounds.
Extracting and viewing them is very easy by the way.
All background camera images are stored in CAMERAxx.PAK
You can use QuickBMS to extract that archive.

They are all raw/uncompressed 320x200 8-bit 256 color images.
To view them as they are in the game you will need the game palette.
It is stored in ITD_RESS.PAK, in a file which is exactly 768 bytes.

Later games (AITD2, AITD3, ...) store palette at the end of camera files (so the file size is 64000 + 768 = 64768 bytes).

More info about what each file contains can be found here : 
https://kb.speeddemosarchive.com/Alone_in_the_Dark_(1-3)/Game_Mechanics_and_Glitches#GAME_FILES

**Comment by demonixis** [comment]
Great thanks!

**Comment by tigrouind** [comment]
FYI : it's now possible to extract background automatically with [PAKExtract](https://github.com/tigrouind/AITD-tools/tree/master/PAKExtract)
