### ISSUE TITLE
Unable to load models 

### ISSUE THREAD

**Issue by dingusdev** [tigrouind/AITD-roomviewer#8]
When I attempt to use the program, it only loads a blue screen. Pressing Tab only shows a black screen. The right click menus still appear, but none of the assets load.

I'm using the files from the original English DOS version of Alone in the Dark. I put the listbody files in \GAMEDATA\LISTBODY, the listanim files in \GAMEDATA\LISTANIM, and the etage files in \GAMEDATA\ETAGE. And still nothing appears.

**Comment by tigrouind** [comment]
You should put original PAK files (eg: LISTBODY.PAK) into GAMEDATA folder, no need of a subfolder.

**Comment by dingusdev** [comment]
When I do that, it displays the message "Cannot find folder GAMEDATA\LISTBODY"

**Comment by tigrouind** [comment]
I guess you are using binaries from last release instead of building it from source.
I have uploaded a new release with latest code. Could you try it ?

**Comment by dingusdev** [comment]
That is correct. I'm using the latest pre-compiled release. That said, I do have Unity's editor installed (albeit an older version, 2019.2.8f1). It does run within the editor, yet it seems that fullscreen mode might be an issue.

**Comment by tigrouind** [comment]
Does it works now ? (using last release I uploaded or Unity editor)

**Comment by dingusdev** [comment]
It works using the latest release now.
