### ISSUE TITLE
Colors Look Off + Stops at Model 26

### ISSUE THREAD

**Issue by PeterG552** [tigrouind/AITD-roomviewer#9]
After the update, it has been working for me, however the colors are a bit off, for example: Edward's skin looks orange-y. Also, for some reason the model viewer stops at model 26 and I can't switch to Emily by pressing Space.

**Comment by tigrouind** [comment]
> I can't switch to Emily by pressing Space.

There was indeed a bug. I have fixed it.

> Colors look off 

I agree there is a slight difference between what is shown in DOSBox and model viewer. However, if you take a screenshot in DOSBox (by pressing CTRL+F5), the colors will be the same as what is shown in model viewer. I'm not sure which colors are the right ones. I suspect the output renderer used in DOSBox to slightly brighten image.

> Model viewer stops at model 26 

I never got that issue. Can you install Unity and report here the error displayed in Console tab ?

**Comment by PeterG552** [comment]
> I agree there is a slight difference between what is shown in DOSBox and model viewer. However, if you take a screenshot in DOSBox (by pressing CTRL+F5), the colors will be the same as what is shown in model viewer.

I saw a screenshot of the model viewer (https://cdn.discordapp.com/attachments/386543982399979534/734425342483365888/unknown.png) and it had the right colors.

> I never got that issue. Can you install Unity and report here the error displayed in Console tab ?

I have Unity installed but don't know much about how it works

**Comment by tigrouind** [comment]
> I have Unity installed but don't know much about how it works

It's really easy. Download [source code](https://github.com/tigrouind/AITD-roomviewer/archive/master.zip) and extract it in a folder. Start Unity. Click on "Open" icon. Choose folder you extracted previously. Once project is open, click on "Play" icon (top center).

**Comment by tigrouind** [comment]
Colors look off and it stops at model 26 because you are using AITD1 demo (not the full game).
AITD1 demo is detected as JITD which use a different palette. This has been fixed.
